[project]
name = "simpleearnapy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kucoin-universal-sdk>=1.3.0",
    "pandas>=2.3.3",
    "python-binance>=1.0.34",
    "python-okx>=0.4.1",
    "requests>=2.32.5",
]
